/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Clothes.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Clothes.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Dress_pile_Dress_pile_u1_v1_0.geometry} material={materials.Dress_pile_u1_v1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Clothes.gltf')
