/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cooker.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cooker(props) {
  const { nodes, materials } = useGLTF('/Cooker.glb')
  return (
    <group {...props} dispose={null} scale={1.5} position={[0, -0.8,0]}>

      <mesh geometry={nodes.stove_panel_UU.geometry} material={materials.stove} position={[0, 0.973, -0.046]} />
      <mesh geometry={nodes.stove_panel_D.geometry} material={materials.stove} position={[0, 0.166, 0.273]} />
      <mesh geometry={nodes.stove_lid_F.geometry} material={materials.stove_glass} position={[0, 0.553, 0.277]} />
      <mesh geometry={nodes.stove_displayglass.geometry} material={materials.stove_glass} position={[0, 0.872, 0.281]} />
      <group position={[0, 0.872, 0.279]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.stove} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.stove_light} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.stove_buttons} />
      </group>
      <mesh geometry={nodes.stove_burner_base_1.geometry} material={materials.stove_burner} position={[-0.134, 0.999, 0.087]} />
      <group position={[-0.134, 0.984, 0.087]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.stove_metal2} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.stove_cooker} />
      </group>
      <mesh geometry={nodes.stove_door_U.geometry} material={materials.stove_glass} position={[0, 1.012, -0.046]} />
      <mesh geometry={nodes.stove_hinge_base.geometry} material={materials.stove_metal} position={[0, 0.973, -0.383]} />
      <group position={[0.001, 0.47, -0.148]}> {/*animatable */}
        <mesh geometry={nodes.Cube018.geometry} material={materials.stove} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials.stove_metal2} />
      </group>
      <mesh geometry={nodes.stove_fan.geometry} material={materials.stove_plastic} position={[0, 0.552, -0.307]} scale={0.328} />
      <mesh geometry={nodes.stove_grill_1.geometry} material={materials.stove_metal} position={[0, 0.638, -0.045]} />
      <mesh geometry={nodes.stove_grill_4.geometry} material={materials.stove_metal} position={[0, 0.379, -0.045]} />
      <mesh geometry={nodes.stove_grill_2.geometry} material={materials.stove_metal} position={[0, 0.555, -0.045]} />
      <mesh geometry={nodes.stove_grill_3.geometry} material={materials.stove_metal} position={[0, 0.46, -0.045]} />
      <mesh geometry={nodes.stove_lightglass_R.geometry} material={materials.stove_glass} position={[-0.268, 0.74, -0.049]} /> {/*make red */}
      <mesh geometry={nodes.stove_light_support_R.geometry} material={materials.stove} position={[-0.268, 0.74, -0.046]} />
      <mesh geometry={nodes.stove_light_L.geometry} material={materials.stove_light} position={[.268, 0.74, -0.049]} /> {/*make red */}
      <mesh geometry={nodes.stove_buttons.geometry} material={materials.stove_buttons} position={[, 0.872, 0.299]} />
      <mesh geometry={nodes.stove_burner_base_4.geometry} material={materials.stove_burner} position={[-0.134, 0.999, -0.18]} />
      <mesh geometry={nodes.stove_burner_base_3.geometry} material={materials.stove_burner} position={[0.134, 0.999, -0.18]} />
      <mesh geometry={nodes.stove_burner_base_2.geometry} material={materials.stove_burner} position={[0.134, 0.999, 0.087]} />
      <group position={[-0.134, 0.984, -0.18]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials.stove_metal2} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials.stove_cooker} />
      </group>
      <group position={[0.134, 0.984, -0.18]}>{/*make red */}
        <mesh geometry={nodes.Cube038.geometry} material={materials.stove_metal2} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials.stove_cooker} />
      </group>
      <group position={[0.134, 0.984, 0.087]}>
        <mesh geometry={nodes.Cube039.geometry} material={materials.stove_metal2} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials.stove_cooker} />
      </group>
      <mesh geometry={nodes.stove_light_support_L.geometry} material={materials.stove_metal2} position={[0.268, 0.74, -0.046]} />
      <mesh geometry={nodes.stove_lightglass_L.geometry} material={materials.stove_glass} position={[0.268, 0.74, -0.049]} />
      <mesh geometry={nodes.stove_light_R.geometry} material={materials.stove_light} position={[-0.268, 0.74, -0.049]} /> 
      <mesh geometry={nodes.stove_hinge_up.geometry} material={materials.stove_metal} position={[0, 1.007, -0.375]} />
      <mesh geometry={nodes.stove_gasplug.geometry} material={materials.stove_metal} position={[-0.301, 0.647, -0.384]} />
      <mesh geometry={nodes.stove_feet.geometry} material={materials.stove_rubber} position={[0, 0.016, 0]} />
      <mesh geometry={nodes.stove_lid_F_handle.geometry} material={materials.stove} position={[0, 0.749, 0.299]} />
    </group>
  )
}

useGLTF.preload('/Cooker.glb')
